### ISSUE TITLE
ItemBinding is null pointer

### ISSUE THREAD

**Issue by LomoLin** [evant/binding-collection-adapter#147]
There are my ViewModel codes:
`val simpleListViewModels = ObservableArrayList<SimpleItemViewModel>()
    val itemView  = ItemBinding.of<SimpleItemViewModel>(BR.simpleViewModel, R.layout.item_simple)

    init {
        for (i in 0..10) {
            simpleListViewModels.add(SimpleItemViewModel())
        }
    }`

and build is successful,but when i run app,it crashed because of null pointer

and error log like this:
`java.lang.IllegalArgumentException: itemBinding must not be null
        at me.tatarka.bindingcollectionadapter2.BindingRecyclerViewAdapters.setAdapter(BindingRecyclerViewAdapters.java:17)
        at com.lomo.juhu.kotlinbaselibrarydemo.databinding.ActivitySimpleListBindingImpl.executeBindings(ActivitySimpleListBindingImpl.java:128)
        at android.databinding.ViewDataBinding.executeBindingsInternal(ViewDataBinding.java:437)
        at android.databinding.ViewDataBinding.executePendingBindings(ViewDataBinding.java:409)
        at android.databinding.ViewDataBinding$7.run(ViewDataBinding.java:194)
        at android.databinding.ViewDataBinding$6.onViewAttachedToWindow(ViewDataBinding.java:162)
        at android.view.View.dispatchAttachedToWindow(View.java:14549)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2837)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2844)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2844)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2844)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2844)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2844)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1407)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1150)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6066)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
        at android.view.Choreographer.doCallbacks(Choreographer.java:672)
        at android.view.Choreographer.doFrame(Choreographer.java:608)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5458)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)`

**Comment by evant** [comment]
Thank you for the report! It looks like your issue is not necessarily with this library, I think you'd be better served asking on a site like stackoverflow where more people would be available to help answer it. If you think it is an actual bug, can you create a sample repo showing the issue?
