### ISSUE TITLE
Null items not working in 0.13

### ISSUE THREAD

**Issue by evant** [evant/binding-collection-adapter#19]
```
java.lang.NullPointerException: collection == null
     at java.util.ArrayList.<init>(ArrayList.java:94)
     at me.tatarka.bindingcollectionadapter.Utils.getListFromCollection(Utils.java:83)
     at me.tatarka.bindingcollectionadapter.BindingViewPagerAdapter.setItems(BindingViewPagerAdapter.java:66)
```

**Comment by evant** [comment]
Fixed in `0.14`
