### ISSUE TITLE
NullPointerException when getting layoutRes()

### ISSUE THREAD

**Issue by rockerhieu** [evant/binding-collection-adapter#25]
I'm not sure if I have used the library correctly or not. Please troubleshoot, thanks!

```
java.lang.NullPointerException
     at me.tatarka.bindingcollectionadapter.ItemViewArg.layoutRes(ItemViewArg.java:37)
     at me.tatarka.bindingcollectionadapter.BindingViewPagerAdapter.instantiateItem(BindingViewPagerAdapter.java:99)
     at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:870)
     at android.support.v4.view.ViewPager.populate(ViewPager.java:1020)
     at android.support.v4.view.ViewPager.populate(ViewPager.java:952)
     at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1474)
     at android.view.View.measure(View.java:16497)
     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
     at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
     at android.view.View.measure(View.java:16497)
     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
     at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
     at android.support.v7.internal.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:124)
     at android.view.View.measure(View.java:16497)
     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
     at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
     at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
     at android.view.View.measure(View.java:16497)
     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
     at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
     at android.view.View.measure(View.java:16497)
     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
     at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
     at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
     at android.view.View.measure(View.java:16497)
     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
     at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
     at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2291)
     at android.view.View.measure(View.java:16497)
     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1912)
     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1109)
     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1291)
     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5600)
     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
     at android.view.Choreographer.doCallbacks(Choreographer.java:574)
     at android.view.Choreographer.doFrame(Choreographer.java:544)
     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
     at android.os.Handler.handleCallback(Handler.java:733)
     at android.os.Handler.dispatchMessage(Handler.java:95)
     at android.os.Looper.loop(Looper.java:136)
     at android.app.ActivityThread.main(ActivityThread.java:5001)
     at java.lang.reflect.Method.invokeNative(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:515)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
     at dalvik.system.NativeStart.main(Native Method)
```

Activity layout file:
```
<layout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto">

  <data>

    <variable
        name="viewModel"
        type="com.example.viewmodel.WalkthroughViewModel"/>
  </data>

  <FrameLayout
      android:layout_width="match_parent"
      android:layout_height="match_parent">

    <android.support.v4.view.ViewPager
        android:id="@+id/viewpager"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:itemView="@{viewModel.itemView}"
        app:items="@{viewModel.items}"/>

    <com.viewpagerindicator.CirclePageIndicator
        android:id="@+id/indicator"
        android:layout_width="fill_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom"
        android:padding="10dip"/>
  </FrameLayout>
</layout>
```

Item layout file:
```
<layout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:tools="http://schemas.android.com/tools">

  <data>

    <variable
        name="item"
        type="com.example.viewmodel.WalkthroughPageViewModel"/>
  </data>

  <LinearLayout
      android:layout_width="match_parent"
      android:layout_height="match_parent"
      android:layout_margin="@dimen/spacing_large"
      android:gravity="center_horizontal"
      android:orientation="vertical">


    <ImageView
        android:id="@+id/avatar"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_gravity="center"
        android:layout_weight="1"
        android:scaleType="centerInside"
        android:src="@{item.image}"
        tools:src="@drawable/reactnative_assets_walkthrough1"/>

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginTop="@dimen/spacing_large"
        android:gravity="center"
        android:textColor="@color/blue_light"
        android:textSize="@dimen/font_large"
        android:text="@{item.title}"
        tools:text="@string/walkthrough_title1"/>

    <View
        android:layout_width="100dp"
        android:layout_height="1dp"
        android:layout_gravity="center_horizontal"
        android:layout_marginTop="@dimen/spacing_large"
        android:background="@color/blue_light"/>

    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="@dimen/spacing_large"
        android:text="@{item.description}"
        tools:text="@string/walkthrough_description1"
        />
  </LinearLayout>
</layout>
```

The code to bind data:
```
ActivityWalkthroughBinding binding = DataBindingUtil.setContentView(this, R.layout.activity_walkthrough);
    binding.executePendingBindings();
    binding.indicator.setViewPager(binding.viewpager);
    WalkthroughViewModel viewModel = new WalkthroughViewModel(Arrays.asList(
        new WalkthroughPageViewModel("title1", "description2", getResources().getDrawable(R.drawable.reactnative_assets_walkthrough1), false),
        new WalkthroughPageViewModel("title2", "description2", getResources().getDrawable(R.drawable.reactnative_assets_walkthrough2), false)
    ));
    binding.setViewModel(viewModel);
```

**Comment by rockerhieu** [comment]
I'm using android-apt 1.8, android gradle plugin 1.5.0.

**Comment by rockerhieu** [comment]
The view model classes:

```
public class WalkthroughViewModel {
  public final ObservableList<WalkthroughPageViewModel> items;

  public final ItemView itemView = ItemView.of(BR.item, R.layout.item_walkthrough);

  public WalkthroughViewModel(List<WalkthroughPageViewModel> items) {
    this.items = new ObservableArrayList<>();
    this.items.addAll(items);
  }
}
```

```
public class WalkthroughPageViewModel {
  public final ObservableField<CharSequence> title;
  public final ObservableField<CharSequence> description;
  public final ObservableField<Drawable> image;
  public final ObservableField<Boolean> hasStartButton;

  public WalkthroughPageViewModel(CharSequence title, CharSequence description, Drawable image, boolean hasStartButton) {
    this.title = new ObservableField<>(title);
    this.description = new ObservableField<>(description);
    this.image = new ObservableField<>(image);
    this.hasStartButton = new ObservableField<>(hasStartButton);
  }
}
```

**Comment by evant** [comment]
If I had to guess its because you are calling executePendingBindings before
binding the data causing it to create the adapter with a null ItemView

**Comment by rockerhieu** [comment]
@evant you're correct. Thanks!
