### ISSUE TITLE
NoSuchMethodException

### ISSUE THREAD

**Issue by croccio** [evant/binding-collection-adapter#34]
java.lang.RuntimeException: java.lang.NoSuchMethodException: <init> [class me.tatarka.bindingcollectionadapter.ItemViewArg]
                                                                        at me.tatarka.bindingcollectionadapter.Utils.createClass(Utils.java:107)
                                                                        at me.tatarka.bindingcollectionadapter.BindingRecyclerViewAdapters$1.create(BindingRecyclerViewAdapters.java:44)
                                                                        at me.tatarka.bindingcollectionadapter.BindingRecyclerViewAdapters.setAdapter(BindingRecyclerViewAdapters.java:27)
                                                                        at com.paybay.quismart.databinding.FragmentGoogleplacesListBinding.executeBindings(FragmentGoogleplacesListBinding.java:135)
                                                                        at android.databinding.ViewDataBinding.executePendingBindings(ViewDataBinding.java:348)
                                                                        at android.databinding.ViewDataBinding$6.run(ViewDataBinding.java:165)
                                                                        at android.databinding.ViewDataBinding$5.onViewAttachedToWindow(ViewDataBinding.java:135)
                                                                        at android.view.View.dispatchAttachedToWindow(View.java:13552)
                                                                        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2689)
                                                                        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2696)
                                                                        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2696)
                                                                        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2696)
                                                                        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2696)
                                                                        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2696)
                                                                        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2696)
                                                                        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2696)
                                                                        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2696)
                                                                        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2696)
                                                                        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1299)
                                                                        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
                                                                        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5891)
                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                        at android.view.Choreographer.doFrame(Choreographer.java:550)
                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:135)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5294)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
                                                                     Caused by: java.lang.NoSuchMethodException: <init> [class me.tatarka.bindingcollectionadapter.ItemViewArg]
                                                                        at java.lang.Class.getConstructor(Class.java:531)
                                                                        at java.lang.Class.getConstructor(Class.java:495)
                                                                        at me.tatarka.bindingcollectionadapter.Utils.createClass(Utils.java:105)
                                                                        at me.tatarka.bindingcollectionadapter.BindingRecyclerViewAdapters$1.create(BindingRecyclerViewAdapters.java:44) 
                                                                        at me.tatarka.bindingcollectionadapter.BindingRecyclerViewAdapters.setAdapter(BindingRecyclerViewAdapters.java:27) 
                                                                        at com.paybay.quismart.databinding.FragmentGoogleplacesListBinding.executeBindings(FragmentGoogleplacesListBinding.java:135) 
                                                                        at android.databinding.ViewDataBinding.executePendingBindings(ViewDataBinding.java:348) 
                                                                        at android.databinding.ViewDataBinding$6.run(ViewDataBinding.java:165) 
                                                                        at android.databinding.ViewDataBinding$5.onViewAttachedToWindow(ViewDataBinding.java:135) 
                                                                        at android.view.View.dispatchAttachedToWindow(View.java:13552) 
                                                                        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2689) 
                                                                        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2696) 
                                                                        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2696) 
                                                                        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2696) 
                                                                        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2696) 
                                                                        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2696) 
                                                                        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2696) 
                                                                        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2696) 
                                                                        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2696) 
                                                                        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2696) 
                                                                        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1299) 
                                                                        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061) 
                                                                        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5891) 
                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767) 
                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:580) 
                                                                        at android.view.Choreographer.doFrame(Choreographer.java:550) 
                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753) 
                                                                        at android.os.Handler.handleCallback(Handler.java:739) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                        at android.os.Looper.loop(Looper.java:135) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5294) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

**Comment by evant** [comment]
Can you be more specific? What error are you getting?

**Comment by croccio** [comment]
sorry i've wrong project. i've edited first post

**Comment by Dev-iL** [comment]
@croccio - which version of the IDE and the are you using? This reminds me of some problem with multidex that I had in 2.0.0-alpha7 & 8 (of Android Studio + gradle plugin)

**Comment by evant** [comment]
Are you still having issues? From the stacktrace I'm guessing you are trying to use a custom adapter class but it doesn't have the required constructor `MyBindingRecyclerViewAdapter(ItemViewArgs<T> args)` to be constructed with reflection. Either add that constructor or use a factory instead.

**Comment by evant** [comment]
Closing this for now, feel free to reopen if you are still having issues.
