### ISSUE TITLE
Unable to use binding collection adapter when header and footer is added to a list view

### ISSUE THREAD

**Issue by amnsinghl** [evant/binding-collection-adapter#57]
I am adding header and footer in a list view using `ListView::addHeaderView` and `ListView::addFooterView`
Getting exception :

```
java.lang.ClassCastException: android.widget.HeaderViewListAdapter cannot be cast to me.tatarka.bindingcollectionadapter.BindingListViewAdapter
    at me.tatarka.bindingcollectionadapter.BindingCollectionAdapters.setAdapter(BindingCollectionAdapters.java:27) ~[na:0.0]
    at to.go.databinding.ContentDrawerBinding.executeBindings(ContentDrawerBinding.java:142) ~[na:0.0]
    at android.databinding.ViewDataBinding.executePendingBindings(ViewDataBinding.java:355) ~[na:0.0]
    at android.databinding.ViewDataBinding$6.run(ViewDataBinding.java:172) ~[na:0.0]
    at android.databinding.ViewDataBinding$7.doFrame(ViewDataBinding.java:238) ~[na:0.0]
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856) ~[na:0.0]
    at android.view.Choreographer.doCallbacks(Choreographer.java:670) ~[na:0.0]
    at android.view.Choreographer.doFrame(Choreographer.java:603) ~[na:0.0]
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844) ~[na:0.0]
    at android.os.Handler.handleCallback(Handler.java:739) ~[na:0.0]
    at android.os.Handler.dispatchMessage(Handler.java:95) ~[na:0.0]
    at android.os.Looper.loop(Looper.java:148) ~[na:0.0]
    at android.app.ActivityThread.main(ActivityThread.java:5417) ~[na:0.0]
    at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) ~[na:0.0]
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) ~[na:0.0]
```

Basically it is failing here 
[BindingListViewAdapter<T> adapter = (BindingListViewAdapter<T>) adapterView.getAdapter();](https://github.com/evant/binding-collection-adapter/blob/master/bindingcollectionadapter/src/main/java/me/tatarka/bindingcollectionadapter/BindingCollectionAdapters.java#L27)
as on adding header or footer the adapter changes to [HeaderListViewAdapter](https://developer.android.com/reference/android/widget/HeaderViewListAdapter.html)

An easy fix for this I found is to replace [BindingListViewAdapter<T> adapter = (BindingListViewAdapter<T>) adapterView.getAdapter();](https://github.com/evant/binding-collection-adapter/blob/master/bindingcollectionadapter/src/main/java/me/tatarka/bindingcollectionadapter/BindingCollectionAdapters.java#L27) with

```
Adapter listAdapter = adapterView.getAdapter();
BindingListViewAdapter<T> adapter;
if (listAdapter instanceof HeaderViewListAdapter) {
    adapter = (BindingListViewAdapter<T>) ((HeaderViewListAdapter) listAdapter)
        .getWrappedAdapter();
} else {
    adapter = (BindingListViewAdapter<T>) adapterView.getAdapter();
}
```

**So i think this fix should be added in the library itself**

Also i have a better way of adding header and footer view in listview

```
@BindingAdapter(value = {"app:footerView", "app:footerViewModel"}, requireAll = false)
public static void addFooterView(ListView listView, ItemView itemView, Object viewModel)
{
    ViewDataBinding footerView = DataBindingUtil
        .inflate(LayoutInflater.from(listView.getContext()), itemView.layoutRes(), null, false);
    if (itemView.bindingVariable() != ItemView.BINDING_VARIABLE_NONE) {
        footerView.setVariable(itemView.bindingVariable(), viewModel);
    }
    listView.addFooterView(footerView.getRoot());
}

@BindingAdapter(value = {"app:headerView", "app:headerViewModel"}, requireAll = false)
public static void addHeaderView(ListView listView, ItemView itemView, Object viewModel)
{
    ViewDataBinding headerView = DataBindingUtil
        .inflate(LayoutInflater.from(listView.getContext()), itemView.layoutRes(), null, false);
    if (itemView.bindingVariable() != ItemView.BINDING_VARIABLE_NONE) {
        headerView.setVariable(itemView.bindingVariable(), viewModel);
    }
    listView.addHeaderView(headerView.getRoot());
}

//in view model
public final ItemView footerItemView = ItemView.of(BR.viewModel, R.layout.footer_view);
public final ItemView headerItemView = ItemView.of(ItemView.BINDING_VARIABLE_NONE, R.layout.header_view);
```

**Comment by amnsinghl** [comment]
So should i generate a pull request for this ?

**Comment by evant** [comment]
Fixed the `ClassCastException`, will have to think more on the headers/footers. It's tricky to get something that doesn't require just as much code as just setting them in code.
