### ISSUE TITLE
also NullPointerException

### ISSUE THREAD

**Issue by YoungDroid** [evant/binding-collection-adapter#58]
Simple demo:
list.xml
`
<RecyclerView 
bind:items="items" 
bind:itemView="itemView"/>
`
i use it ok.
but when i use 
`
<include layout:list.xml bind:listViewModel="listViewModel"/> 
`
it throw NullPointerException

`
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   java.lang.NullPointerException
                                                                       at me.tatarka.bindingcollectionadapter.ItemViewArg.select(ItemViewArg.java:29)
                                                                       at me.tatarka.bindingcollectionadapter.BindingRecyclerViewAdapter.getItemViewType(BindingRecyclerViewAdapter.java:157)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4960)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4913)
                                                                       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
                                                                       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1414)
                                                                       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
                                                                       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
                                                                       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3260)
                                                                       at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:2788)
                                                                       at android.view.View.measure(View.java:15518)
`

just nest listView or RecyclerView in <include/>

how to fix it? thanks very much

**Comment by yz253233154** [comment]
i'm sure itemViewModel is OK
other like : TextView Button work ok;
only ListView or RecyclerView not work

**Comment by yz253233154** [comment]
i'm sure listViewModel is OK
other like : TextView Button work ok;
only ListView or RecyclerView not work

**Comment by evant** [comment]
This isn't enough to go off of, can you link to a sample project?

**Comment by yz253233154** [comment]
https://github.com/yz253233154/RxAndroid

here, crash demo.
thank u~

**Comment by evant** [comment]
Thanks for the sample. It's actually not crashing for me when I build and run it. (Running on 6.0 emulator). Do you know if this might be device/api level specific? Could you upload an apk that is crashing so I can compare?

**Comment by yz253233154** [comment]
2 kinds of situation in the code, all they not crash ? 

That's too confused. 

i try code on 4.4, 5.0 ( no device for 6.0 ). 


and i uploaded 2 apk,  one crash / on run OK .
> crash code will crash
> not crash code run ok

```

// Crash 
ViewDataBinding binding = DataBindingUtil.setContentView( this,R.layout.activity_main );
binding.setVariable( BR.viewModel, new MainViewModel( this ) );

// Not Crash 
ViewDataBinding binding = DataBindingUtil.setContentView( this,R.layout.layout_include );
binding.setVariable( BR.includeViewModel, new IncludeViewModel( this ) );

```

> only this difference.

i'm sure that not because of device/api level specific, i can run one
of the 2 situation.

**Comment by yz253233154** [comment]
sorry, i try CrashDemo on 5.0 .
It won't crash.
i don't understand thy.

can u try it on device below 5.0 ? 
i can't find the reason.

**Comment by xianjixin** [comment]
I've had the same problem.
I debug the test to find out the following problem.

 @Override
    public int getItemViewType(int position) {
        itemViewArg.select(position, items.get(position));
        return itemViewArg.layoutRes();
    }

itemViewArg is null;
but device on 5.0  is not null;
itemViewArg is null when device is 4.1.1


` FATAL EXCEPTION: main  java.lang.NullPointerException
    at me.tatarka.bindingcollectionadapter.ItemViewArg.layoutRes(ItemViewArg.java:37)
    at me.tatarka.bindingcollectionadapter.BindingRecyclerViewAdapter.getItemViewType(BindingRecyclerViewAdapter.java:181)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4664)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4617)
at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1994)
 at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1390)
at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1353)
at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:574)
at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3028)
at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:2625)`

**Comment by yz253233154** [comment]
here, i solved the bug.
and i found the code in 

```
public class BindingRecyclerViewAdapters {
    // RecyclerView
    @SuppressWarnings("unchecked")
    @BindingAdapter(value = { "itemView", "items", "adapter", "itemIds", "viewHolder" }, requireAll = false)
    public static < T > void setAdapter( RecyclerView recyclerView, ItemViewArg< T > arg, List< T > items, BindingRecyclerViewAdapterFactory factory, BindingRecyclerViewAdapter.ItemIds< T > itemIds, BindingRecyclerViewAdapter.ViewHolderFactory viewHolderFactory ) {
        if ( arg == null ) {
            throw new IllegalArgumentException( "itemView must not be null" );
        }
        if ( factory == null ) {
            factory = BindingRecyclerViewAdapterFactory.DEFAULT;
        }
            BindingRecyclerViewAdapter< T > adapter = ( BindingRecyclerViewAdapter< T > ) recyclerView.getAdapter();
            if ( adapter == null ) {
                adapter = factory.create( recyclerView, arg );
                adapter.setItems( items );
                adapter.setItemIds( itemIds );
                adapter.setViewHolderFactory( viewHolderFactory );
                recyclerView.setAdapter( adapter );
            } else {
                adapter.setItems( items );
            }
    }

    @BindingAdapter("layoutManager")
    public static void setLayoutManager( RecyclerView recyclerView, LayoutManagers.LayoutManagerFactory layoutManagerFactory ) {
        recyclerView.setLayoutManager( layoutManagerFactory.create( recyclerView ) );
    }

    @BindingConversion
    public static BindingRecyclerViewAdapterFactory toRecyclerViewAdapterFactory( final String className ) {
        return new BindingRecyclerViewAdapterFactory() {
            @Override
            public < T > BindingRecyclerViewAdapter< T > create( RecyclerView recyclerView, ItemViewArg< T > arg ) {
                return Utils.createClass( className, arg );
            }
        };
    }
}
```

should add a check of 

> ItemViewArg< T >.getItemView()

```
        if ( arg.getItemView() != null ) {
            BindingRecyclerViewAdapter< T > adapter = ( BindingRecyclerViewAdapter< T > ) recyclerView.getAdapter();
            if ( adapter == null ) {
                adapter = factory.create( recyclerView, arg );
                adapter.setItems( items );
                adapter.setItemIds( itemIds );
                adapter.setViewHolderFactory( viewHolderFactory );
                recyclerView.setAdapter( adapter );
            } else {
                adapter.setItems( items );
            }
        }
```

and it work ok on all device.

it's because of device below 5.0 when use 
`<include/>`
bind the ViewModel will call this method when itemView not ready.
you can break in this method, and verify.

**Comment by evant** [comment]
Yeah I'm seeing the issue with the include. Was able to reproduce with a similar test case even without this lib. I'll work on a work around, but I think I'm also going to file an issue about the databinding lib.

**Comment by evant** [comment]
You can follow the issue here https://code.google.com/p/android/issues/detail?id=220801

**Comment by joxad** [comment]
Hi @evant . We 've got the same problem here. Works very nice for 5 and more but below it crashes.
Any thought about adding the work around in the lib of @YoungDroid ?
I can do a PR as well if I found some time today.

**Comment by joxad** [comment]
Actually after further investigation, the problem is for the android version below kitkat.

**Comment by evant** [comment]
I believe this is fixed when using the latest android gradle plugin, have you tested?

**Comment by joxad** [comment]
I have gradle plugin 2.2.3
and gradle-2.14.1

**Comment by evant** [comment]
This was supposedly fixed, feel free to re-open if you are still having issues.

**Comment by ANPez** [comment]
I just had this issue using latest 3.0 beta with androidx. "Fixed" it by providing a default value for binding in included layout like so:

`app:itemBinding="@{itemBinding ?? ItemBinding.of(ItemBinding.VAR_NONE, R.layout.some_list_cell)}`
