### ISSUE TITLE
Using an item animator results in crashes in v1.+

### ISSUE THREAD

**Issue by ANPez** [evant/binding-collection-adapter#64]
If using verbatim, everything works great. If I add an item animator to the recyclerview, in 1.+ it crashes the app, and on 2.0.0-beta2 works.
The test is as follows:
1. Attach the item animator (I'm using jp.wasabeef.recyclerview.animators.OvershootInRightAnimator).
2. Load the list. Everything works fine.
3. Reload the list (I do this with a SwipeRefreshLayout).
4. When reloading the list, the items are cleared from the ObservableList, and recreated. At this step, it reloads ok, but in logcat I see lots of this:

View: isRecyclable decremented below 0: unmatched pair of setIsRecyable() calls for ViewHolder{8da5b74 position=0 id=-1, oldPos=-1, pLpos:-1}```

I'm getting this on 2.0.0-beta2 too.
1. If I reload again, the app crashes with the following error:

`java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder{7c63ec8 position=0 id=-1, oldPos=-1, pLpos:-1 no parent}
                                                                               at android.support.v7.widget.RecyclerView$5.attachViewToParent(RecyclerView.java:692)
                                                                               at android.support.v7.widget.ChildHelper.attachViewToParent(ChildHelper.java:239)
                                                                               at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:7096)
                                                                               at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7073)
                                                                               at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7061)
                                                                               at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1428)
                                                                               at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
                                                                               at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
                                                                               at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3315)
                                                                               at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3124)
                                                                               at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3568)
                                                                               at android.view.View.layout(View.java:16636)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                               at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:613)`

**Comment by evant** [comment]
not sure if this is still an issue. If it is, can you re-open and provide a sample project?
