### ISSUE TITLE
Support for non-`static` `BindingAdapter`s (`DataBindingComponent`)

### ISSUE THREAD

**Issue by DavidDTA** [evant/binding-collection-adapter#85]
In order to use non-`static` `BindingAdapter`s with collection items, we need to provide a `DataBindingComponent` to `DataBindingUtil.inflate`.

When using the 4-argument `inflate` method, we get the following crash during inflation:
```
java.lang.IllegalStateException: Required DataBindingComponent is null in class ActivityMainGridCellBinding. A BindingAdapter in com.example.activity.BaseActivity is not static and requires an object to use, retrieved from the DataBindingComponent. If you don't use an inflation method taking a DataBindingComponent, use DataBindingUtil.setDefaultComponent or make all BindingAdapter methods static.
        at android.databinding.ViewDataBinding.ensureBindingComponentIsNotNull(ViewDataBinding.java:554)
        at com.example.databinding.ActivityMainGridCellBinding.<init>(ActivityMainGridCellBinding.java:24)
        at com.example.databinding.ActivityMainGridCellBinding.bind(ActivityMainGridCellBinding.java:132)
        at android.databinding.DataBinderMapper.getDataBinder(DataBinderMapper.java:13)
        at android.databinding.DataBindingUtil.bind(DataBindingUtil.java:185)
        at android.databinding.DataBindingUtil.inflate(DataBindingUtil.java:120)
        at android.databinding.DataBindingUtil.inflate(DataBindingUtil.java:88)
        at me.tatarka.bindingcollectionadapter2.BindingRecyclerViewAdapter.onCreateBinding(BindingRecyclerViewAdapter.java:72)
        at me.tatarka.bindingcollectionadapter2.BindingRecyclerViewAdapter.onCreateViewHolder(BindingRecyclerViewAdapter.java:103)
        at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6367)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5555)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
        at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
        at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
        at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3025)
        at android.view.View.measure(View.java:19730)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
        at android.view.View.measure(View.java:19730)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
        at android.view.View.measure(View.java:19730)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
        at android.view.View.measure(View.java:19730)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
        at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:393)
        at android.view.View.measure(View.java:19730)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:19730)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
        at android.view.View.measure(View.java:19730)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:687)
        at android.view.View.measure(View.java:19730)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2271)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1358)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1607)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6301)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
        at android.view.Choreographer.doCallbacks(Choreographer.java:683)
        at android.view.Choreographer.doFrame(Choreographer.java:619)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by DavidDTA** [comment]
A limited workaround is to use `DataBindingUtil.setDefaultComponent`, although this will only work if all bindings use the same component.

**Comment by evant** [comment]
You can subclass the adatper and override `onCreateBinding` to inflate with the component.
