### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter

### ISSUE THREAD

**Issue by gingo** [evant/binding-collection-adapter#90]
I'm getting a lot of this errors:
```
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{2641db7 position=12 id=41, oldPos=0, pLpos:0 scrap [attachedScrap] tmpDetached no parent}
  at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5297)
  at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5479)
  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
  at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
  at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
  at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
  at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
  at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3534)
  at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3310)
  at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1648)
  at android.support.v7.widget.RecyclerView$1.run(RecyclerView.java:343)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
  at android.view.Choreographer.doCallbacks(Choreographer.java:683)
  at android.view.Choreographer.doFrame(Choreographer.java:616)
  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
  at android.os.Handler.handleCallback(Handler.java:751)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:154)
  at android.app.ActivityThread.main(ActivityThread.java:6077)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```
It appears for example when permission dialog is opened in the middle of "add items animation".

**Comment by camino2007** [comment]
Me too:

> java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 11(offset:11).state:20
> 	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5504)
> 	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
> 	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
> 	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
> 	at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
> 	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
> 	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
> 	at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
> 	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
> 	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
> 	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)

Occurs until now only on >= 6.0.1 devices

**Comment by evant** [comment]
Are you only modifying the source list on the main thread? Can you post a sample that reproduces?

**Comment by evant** [comment]
Closing for lack of response, feel free to re-open if you are still having issues.
